include:
  - project: devsecops/cicd/pipeline
    ref: v19.0.0
    file: main.yml

variables:
  SRC_DIR: "safe_autonomy_simulation"
  ACT3_SECRETS_POETRY: |
    [http-basic.act3-rl]
    username = "gitlab-ci-token"
    password = "$CI_JOB_TOKEN"
  ACT3_SECRETS_GITLAB: "gitlab-ci-token:$CI_JOB_TOKEN"

mkdocs:
  image:
    name: $CI_REGISTRY_IMAGE/cicd:ci-$CI_PIPELINE_ID
  needs:
    - build image
  before_script:
    - "poetry install --only docs"
  allow_failure: true

pages:
  allow_failure: true

build tagged image:
  parallel:
    matrix:
      - TARGET_STAGE: build
        DESTINATION_PATH: /releases
      - TARGET_STAGE: develop
        DESTINATION_PATH: /development/$TARGET_STAGE
      - TARGET_STAGE: package
        DESTINATION_PATH: /releases/$TARGET_STAGE
      - TARGET_STAGE: hub-coder-user
        DESTINATION_PATH: /development/$TARGET_STAGE
