include:
  - project: devsecops/cicd/pipeline
    ref: v8.2.19
    file: main.yml

variables:
  PIP_INDEX_URL: https://devpi.lion.act3-ace.ai/root/pypi/+simple/
  SRC_DIR: safe_autonomy_simulation

mkdocs:
  allow_failure: true

build image: 
  variables:
      TARGET_IMAGE: cicd

build tagged image:
  variables: 
      TARGET_STAGE: build
      DESTINATION_PATH: /releases

build development image:
  extends: build tagged image
  variables: 
    TARGET_STAGE: develop
    DESTINATION_PATH: /development/$TARGET_STAGE

build package image:
  extends: build tagged image
  variables: 
    TARGET_STAGE: package
    DESTINATION_PATH: /releases/$TARGET_STAGE



