secrets:
  ACT3_SECRETS_POETRY:
    # XDG_CONFIG_HOME is set by direnv
    file: ${XDG_CONFIG_HOME:-$HOME/.config}/pypoetry/auth.toml
    name: ACT3_SECRETS_POETRY
  ACT3_SECRETS_GITLAB:
    # ACT3_SECRETS_GITLAB is set by direnv
    environment: "ACT3_SECRETS_GITLAB"

services:
  # creates an image with the source code and root package installed
  build:
    image: "reg.git.act3-ace.com/rta/safe-autonomy-stack/safe-autonomy-simulation/releases:latest"
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      secrets:
        - ACT3_SECRETS_POETRY
    user: 1000:1000
  # creates an image used in the cicd pipeline
  ci:
    image: "reg.git.act3-ace.com/rta/safe-autonomy-stack/safe-autonomy-simulation/cicd:latest"
    build:
      context: .
      dockerfile: Dockerfile
      target: ci
      secrets:
        - ACT3_SECRETS_POETRY
    user: 1000:1000
  # creates an image that can be used in ASCE Hub, does not run locally (yet)
  hub-coder-user:
    image: "reg.git.act3-ace.com/rta/safe-autonomy-stack/safe-autonomy-simulation/development:latest"
    working_dir: /opt/project
    build:
      context: .
      dockerfile: Dockerfile
      target: hub-coder-user
      secrets:
        - ACT3_SECRETS_POETRY
        - ACT3_SECRETS_GITLAB
      args:
        OCI_REGISTRY: reg.git.act3-ace.com
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCK}
      DISPLAY: ${DISPLAY}
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      # *** NOTE THIS IS LINUX SPECIFIC ITEM *** Updates needed for Virtual based setups
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      # for development, link the host folder containing code to /opt/project in container
      - "./:/opt/project"
    ports:
      - 8888:8888
      - 8000:8000

#########################################################################################
# Volumes Stores
#########################################################################################
volumes:
  vscode-server-extensions:
  vscode-server-extensions-insiders:

#########################################################################################
# Network
#########################################################################################
networks:
  default:
    name: act3
