site_name: safe-autonomy-simulation
site_author: ACT3
repo_url: https://git.act3-ace.com/rta/safe-autonomy-stack/safe-autonomy-simulation

plugins:
  - search
  - macros


markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - "Getting Started": index.md
  - "safe-autonomy-simulation":
    - safe_autonomy_simulation/hello_world.md
    - safe_autonomy_simulation/numpy_example.md

theme: readthedocs

# Macros info: https://github.com/fralau/mkdocs_macros_plugin#how-to-use-the-macros-plugin
extra:
  foo: bar
