site_name: Safe Autonomy Simulation
site_author: ACT3
repo_url: https://git.act3-ace.com/rta/safe-autonomy-stack/safe-autonomy-simulation

plugins:
  - search
  - macros
  - inari:
      module: safe_autonomy_simulation # required

markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - "Getting Started": index.md
  - "Safe Autonomy Simulation":
    - safe_autonomy_simulation/base_models-py.md
    - safe_autonomy_simulation/simulator-py.md
    - safe_autonomy_simulation/docking/simulator-py.md
    - safe_autonomy_simulation/docking/point_model-py.md

theme: readthedocs

# Macros info: https://github.com/fralau/mkdocs_macros_plugin#how-to-use-the-macros-plugin
extra:
  foo: bar
